name: pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write  # Required for certain actions to authenticate securely

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          exit 0

  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mart337i/egeskov-olsen.dk:latest
            ghcr.io/mart337i/egeskov-olsen.dk:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" > ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: qnote
          file: compose.yaml
          host: qnote.dk
          user: deploy
          ssh_key: ${{ secrets.DOCKER_SSH_KEY }}
          env_file: ./envfile
          registry_auth: true
          registry_host: ghcr.io
          registry_user: mart337i
          registry_pass: ${{ secrets.GHCR_PASS }}